{application, mongosql,
 [{description, "MongoSQL"},
  {vsn, "0.0.3"},
  {modules, [mongosql_conn,
             mongosql_sem,
             sql92_parser,
             sql92_scan,
             mongosql_cli,
             mongosql_join]},
  {registered,[]},
  {applications, [kernel,stdlib]},
  {env, []}]}.
